version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/books-app
    ports:
      - 5173:5173
    image: app:react
    container_name: books-app_container
    command: npm start